import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/DarkMode";
import { ModeToggle } from "@/components/ui/ToggleMode";
import Footer from "@/components/footer/footer";
import Scroll from "@/components/scroll/Scroll";
// import LanguageSwitcher from "@/components/languages/lang";

const inter = Inter({
  weight: ["100",'200',"300","600","700","900","400","800","500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mohammad's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,params
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-gray-100 dark:bg-[#0d0d1f]`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
            <Scroll />
            <ModeToggle />
            {/* <LanguageSwitcher /> */}
            {children}
            <Footer />
          </ThemeProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import {  Inter } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/components/DarkMode";
// import { ModeToggle } from "@/components/ui/ToggleMode";
// import { NextIntlProvider } from 'next-intl';
// import Footer from "@/components/footer/footer";
// import Scroll from "@/components/scroll/Scroll";

// const inter = Inter({
//   weight: ["100",'200',"300","600","700","900","400","800","500"],
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Mohammad's Portfolio",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,params
// }: Readonly<{
//   children: React.ReactNode;
//   params: any;
// }>) {
//   const messages = require(`../locales/${params.locale}.json`);
//   return (
//     <html lang={params.locale} suppressHydrationWarning>
//       <body
//         className={`${inter.className} antialiased bg-gray-100 dark:bg-[#0d0d1f]`}
//       >
//         <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             <Scroll />
//             <ModeToggle />
//             {children}
//             <Footer />
//           </ThemeProvider>
//       </body>
//     </html>
//   );
// }
