import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/DarkMode";
import { ModeToggle } from "@/components/ui/ToggleMode";
import Responsive from "@/components/navbar/Responsive";
import Footer from "@/components/footer/footer";
import Scroll from "@/components/scroll/Scroll";

const inter = Inter({
  weight: ["100",'200',"300","600","700","900","400","800","500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mohammad's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-gray-100 dark:bg-[#0d0d1f]`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Scroll />
            <ModeToggle />
            {children}
            <Footer />
          </ThemeProvider>
      </body>
    </html>
  );
}
